ignite {
  network {
    port: 3344
    nodeFinder.netClusterNodes = ["ignite3-node1:3344", "ignite3-node2:3344", "ignite3-node3:3344"]
  }
  storage {
    profiles = [
      {
        name = rocksDbProfile
        engine = rocksdb
      }
    ]
  }
}
