exporters:
  otlphttp/dynatrace:
    endpoint: ${env:DT_ENDPOINT}
    headers:
      Authorization: Api-Token ${env:DT_API_TOKEN}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp/dynatrace]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp/dynatrace]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp/dynatrace]

